line-length = 79
exclude = ["migrations", "venv"]


[lint]
select = [
    "N",  # PEP8 Naming Conventions (naming)
    "F",  # Pyflakes (pyflakes)
    "W",  # Pycodestyle Warnings (pycodestyle_warnings)
    "E",  # Pycodestyle Errors (pycodestyle_errors)
    "I",  # Import Sorting (isort)
    "Q",  # Quote Consistency (flake8-quotes)
    "TID",  # Tidy Imports (flake8-tidy-imports)
    "COM",  # Commas (flake8-commas)
    "C4",  # Comprehensions (flake8-comprehensions)
    "ERA",  # Eradicate (dead code detection)
    "RET",  # Returns (flake8-return)
    "PTH",  # Pathlib (flake8-use-pathlib)
    "ISC",  # Implicit String Concatenation (flake8-implicit-str-concat)
    "C90",  # McCabe Complexity (mccabe)
    "T20",  # Print Statements (flake8-print)
    "SIM"  # Simplify (flake8-simplify)
]

[format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"


[lint.isort]
force-sort-within-sections = true
# known-first-party = your_apps


[lint.flake8-quotes]
inline-quotes = "single"


[lint.flake8-tidy-imports]
ban-relative-imports = "all"
