name: Ruff

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Run Ruff
        uses: astral-sh/ruff-action@v3.2.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: ruff format --check